AWSTemplateFormatVersion: "2010-09-09"
Description: video-transcoder

Parameters:
  InputBucketName:
    Description: Initial files are deployed here
    Type: String
    Default: video-transcoder-input-bucket
  OutputBucketName:
    Description: Files that are the output of the lambda are here
    Type: String
    Default: video-transcoder-output-bucket
Resources:
  InputBucket: 
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref InputBucketName
  OutputBucket: 
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref OutputBucketName
  
  EventRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - 'AWS API Call via CloudTrail'
        detail:
          eventSource:
            - s3.amazonaws.com
          eventName:
            - CopyObject
            - PutObject
            - CompleteMultipartUpload
          requestParameters:
            bucketName:
              - !Ref InputBucketName
            key:
              - ""
        Targets:
          - Arn: !GetAtt VideoTranscoder.Arn
            Id: VideoTranscoder
  VideoTranscoder:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: VideoTranscoder
      Handler: video-transcoder.lambda_handler
      Runtime: python3.12
      Role: !GetAtt LambdaFunctionRole.Arn
      MemorySize: 1024
      CodeUri: ./
  LambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: AppendToLogsPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: "*"